import React, { Component } from 'react';

class SCPSummary extends Component {
  render() {
    return (
    <div className="row">
        <div className="col-12">
        <div className="card">
                <div className="card-body">
                    <h5 className="card-title indicatortitle">Kisumu County - May 2018</h5>
                    <div className="table-responsive">
                        <div id="zero_config_wrapper" className="dataTables_wrapper"><div className="dataTables_length" id="zero_config_length"><label>Show <select name="zero_config_length" aria-controls="zero_config" className=""><option value="10">10</option><option value="25">25</option><option value="50">50</option><option value="100">100</option></select> entries</label></div><div id="zero_config_filter" className="dataTables_filter"><label>Search:<input type="search" className="" placeholder="" aria-controls="zero_config"/></label></div><table id="zero_config" className="table table-striped table-bordered indicatorsumm dataTable" role="grid" aria-describedby="zero_config_info">
                            <thead>
                                <tr role="row"><th className="sorting_asc" tabindex="0" aria-controls="zero_config" rowspan="1" colspan="1" style={{width: '244.017px'}} aria-label="Parameter: activate to sort column descending" aria-sort="ascending"><b>Parameter</b></th><th className="sorting" tabindex="0" aria-controls="zero_config" rowspan="1" colspan="1" style={{width: '135.483px'}} aria-label="Item: activate to sort column ascending"><b>Item</b></th><th className="sorting" tabindex="0" aria-controls="zero_config" rowspan="1" colspan="1" style={{width: '139.267px'}} aria-label="Num: activate to sort column ascending"><b>Num</b></th><th className="sorting" tabindex="0" aria-controls="zero_config" rowspan="1" colspan="1" style={{width: '126.3px'}} aria-label="Den: activate to sort column ascending"><b>Den</b></th><th className="sorting" tabindex="0" aria-controls="zero_config" rowspan="1" colspan="1" style={{width: '169.2px'}} aria-label="Result: activate to sort column ascending"><b>Result</b></th><th className="sorting" tabindex="0" aria-controls="zero_config" rowspan="1" colspan="1" style={{width: '170.2px'}} aria-label="Target: activate to sort column ascending"><b>Target</b></th><th className="sorting" tabindex="0" aria-controls="zero_config" rowspan="1" colspan="1" style={{width: '256.117px'}} aria-label="Acceptable: activate to sort column ascending"><b>Acceptable</b></th></tr>
                            </thead>
                            <tbody><tr role="row" className="odd"><td className="sorting_1">HFs over-stocked</td><td>Artemether-Lumefantrine 20/120 Tabs 6s MOS</td><td>53</td><td>230</td><td>23.0%</td><td>5%</td><td>15%</td></tr><tr role="row" className="even"><td className="sorting_1">HFs over-stocked</td><td>Artemether-Lumefantrine 20/120 Tabs 12s MOS</td><td>9</td><td>230</td><td>3.9%</td><td>5%</td><td>15%</td></tr><tr role="row" className="odd"><td className="sorting_1">HFs over-stocked</td><td>Artemether-Lumefantrine 20/120 Tabs 18s MOS</td><td>8</td><td>230</td><td>3.5%</td><td>5%</td><td>15%</td></tr><tr role="row" className="even"><td className="sorting_1">HFs over-stocked</td><td>Artemether-Lumefantrine 20/120 Tabs 24s MOS</td><td>98</td><td>230</td><td>42.6%</td><td>5%</td><td>15%</td></tr><tr role="row" className="odd"><td className="sorting_1">HFs stocked according to plan</td><td>Artemether-Lumefantrine 20/120 Tabs 6s MOS</td><td>31</td><td>230</td><td>13.5%</td><td>90%</td><td>70%</td></tr><tr role="row" className="even"><td className="sorting_1">HFs stocked according to plan</td><td>Artemether-Lumefantrine 20/120 Tabs 12s MOS</td><td>15</td><td>230</td><td>6.5%</td><td>90%</td><td>70%</td></tr><tr role="row" className="odd"><td className="sorting_1">HFs stocked according to plan</td><td>Artemether-Lumefantrine 20/120 Tabs 18s MOS</td><td>8</td><td>230</td><td>3.5%</td><td>90%</td><td>70%</td></tr><tr role="row" className="even"><td className="sorting_1">HFs stocked according to plan</td><td>Artemether-Lumefantrine 20/120 Tabs 24s MOS</td><td>8</td><td>230</td><td>3.5%</td><td>90%</td><td>70%</td></tr><tr role="row" className="odd"><td className="sorting_1">HFs under-stocked</td><td>Artemether-Lumefantrine 20/120 Tabs 6s MOS</td><td>38</td><td>230</td><td>16.5%</td><td>5%</td><td>15%</td></tr><tr role="row" className="even"><td className="sorting_1">HFs under-stocked</td><td>Artemether-Lumefantrine 20/120 Tabs 12s MOS</td><td>65</td><td>230</td><td>28.3%</td><td>5%</td><td>15%</td></tr></tbody>
                            <tfoot>
                                <tr><th rowspan="1" colspan="1"><select><option value=""></option><option value="HFs over-stocked">HFs over-stocked</option><option value="HFs stocked according to plan">HFs stocked according to plan</option><option value="HFs under-stocked">HFs under-stocked</option><option value="HFs with a stock out">HFs with a stock out</option></select></th><th rowspan="1" colspan="1"><select><option value=""></option><option value="Artemether-Lumefantrine 20/120 Tabs 12s MOS">Artemether-Lumefantrine 20/120 Tabs 12s MOS</option><option value="Artemether-Lumefantrine 20/120 Tabs 18s MOS">Artemether-Lumefantrine 20/120 Tabs 18s MOS</option><option value="Artemether-Lumefantrine 20/120 Tabs 24s MOS">Artemether-Lumefantrine 20/120 Tabs 24s MOS</option><option value="Artemether-Lumefantrine 20/120 Tabs 6s MOS">Artemether-Lumefantrine 20/120 Tabs 6s MOS</option></select></th><th rowspan="1" colspan="1"><select><option value=""></option><option value="10">10</option><option value="11">11</option><option value="15">15</option><option value="17">17</option><option value="21">21</option><option value="31">31</option><option value="38">38</option><option value="44">44</option><option value="53">53</option><option value="65">65</option><option value="8">8</option><option value="9">9</option><option value="96">96</option><option value="98">98</option></select></th><th rowspan="1" colspan="1"><select><option value=""></option><option value="230">230</option></select></th><th rowspan="1" colspan="1"><select><option value=""></option><option value="13.5%">13.5%</option><option value="16.5%">16.5%</option><option value="19.1%">19.1%</option><option value="23.0%">23.0%</option><option value="28.3%">28.3%</option><option value="3.5%">3.5%</option><option value="3.9%">3.9%</option><option value="4.3%">4.3%</option><option value="4.8%">4.8%</option><option value="41.7%">41.7%</option><option value="42.6%">42.6%</option><option value="6.5%">6.5%</option><option value="7.4%">7.4%</option><option value="9.1%">9.1%</option></select></th><th rowspan="1" colspan="1"><select><option value=""></option><option value="0%">0%</option><option value="5%">5%</option><option value="90%">90%</option></select></th><th rowspan="1" colspan="1"><select><option value=""></option><option value="10%">10%</option><option value="15%">15%</option><option value="70%">70%</option></select></th></tr>
                            </tfoot>
                        </table><div className="dataTables_info" id="zero_config_info" role="status" aria-live="polite">Showing 1 to 10 of 16 entries</div><div className="dataTables_paginate paging_simple_numbers" id="zero_config_paginate"><a className="paginate_button previous disabled" aria-controls="zero_config" data-dt-idx="0" tabindex="0" id="zero_config_previous">Previous</a><span><a className="paginate_button current" aria-controls="zero_config" data-dt-idx="1" tabindex="0">1</a><a className="paginate_button " aria-controls="zero_config" data-dt-idx="2" tabindex="0">2</a></span><a className="paginate_button next" aria-controls="zero_config" data-dt-idx="3" tabindex="0" id="zero_config_next">Next</a></div></div>
                    </div>

                </div>
            </div>
        </div>
    </div>

    );
  }
}

export default SCPSummary;
